[package]
name = "goat_bot"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
getrandom = { version = "0.2", features = ["js"] }
goat_api = { path = "../goat_api" }
log = "0.4"
rand = "0.8"
tokio = { version = "1.32", features = ["sync"] }
