[package]
name = "goat_bot"
version = "0.0.0"
edition = "2021"

[dependencies]
goat_api = { path = "../goat_api" }
log = "0.4"
rand = "0.8"
rayon = "1.7"
tokio = { version = "1.32", features = ["sync"] }
