[package]
name = "goat_api"
version = "0.0.0"
edition = "2021"

[dependencies]
log = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
smallvec = { version = "1.11", features = ["serde", "union"] }
thiserror = "1.0"

[dev-dependencies]
itertools = "0.11"
